apiVersion: v1
kind: Secret
metadata:
  name: azure-creds
  namespace: upbound-system
type: Opaque
stringData:
  "credentials": |-
    {
      "clientId": "b9055649-9115-41ca-b1ba-0fc10f7a0e03",
      "clientSecret": "NId8Q~xpLShKb6ujBJA5SmAseSPPGSALuQ~LPal_",
      "tenantId": "9309a99d-2f4f-4453-8b1d-101c3c3374dc",
      "subscriptionId": "08f4b432-73a9-48f4-a33c-c550d6057857" 
    }
---
apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: terraform-azure
spec:
  credentials:
    # Filename has to comply with below naming convention:
    # - Files named exactly terraform.tfvars or terraform.tfvars.json.
    # - Any files with names ending in .auto.tfvars or .auto.tfvars.json.
    - filename: terraform.tfvars.json
      source: Secret
      secretRef:
        namespace: upbound-system
        name: azure-creds
        key: credentials
  configuration: |
        terraform {
          required_providers {
            azurerm = {
              source = "hashicorp/azurerm"
              version = "3.78.0"
            }
          }
          
          backend "kubernetes" {
            secret_suffix     = "providerconfig-azure-westeurope"
            namespace         = "upbound-system"
            in_cluster_config = true
          }
        }
        variable "subscriptionId" {
          type = string
        }

        variable "tenantId" {
          type = string
        }

        variable "clientId" {
          type = string
        }

        variable "clientSecret" {
          type = string
        }

        provider "azurerm" {
          subscription_id = var.subscriptionId
          tenant_id = var.tenantId
          client_id = var.clientId
          client_secret = var.clientSecret
          features {}
        }
