apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: amcop-grafana-datasource
  namespace: tenant
spec:
  instanceSelector:
    matchLabels:
      app: amcop-grafana
  datasource:
    name: amcop-cortex
    type: prometheus
    access: proxy
    url: http://cortex-query-frontend.amcop-system:8080/api/prom
    isDefault: false
    jsonData:
      'tlsSkipVerify': true
      'timeInterval': "5s"
      #      header for selecting the tenant bucket for cortex
      'httpHeaderName1': "X-Scope-OrgID" 
    secureJsonData:
      'httpHeaderValue1': tenant # kpt-set: ${orgid}
    editable: true
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: amcop-grafana-datasource-local
  namespace: tenant
spec:
  datasource:
    access: proxy
    editable: true
    isDefault: false
    name: prometheus
    type: prometheus
    url: http://amcop-prometheus-service:9090
  instanceSelector:
    matchLabels:
      app: amcop-grafana
