apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: amcop-grafana-datasource
  namespace: tenant
spec:
  instanceSelector:
    matchLabels:
      app: amcop-grafana
  datasource:
    name: amcop-prom
    type: prometheus
    access: proxy
    url: http://amcop-prometheus-service:9090
