# Source: grafana-operator/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: grafana-operator-metrics-service
  namespace: amcop-system
  labels:
    app.kubernetes.io/name: grafana-operator
    app.kubernetes.io/version: 5.0.0
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    app.kubernetes.io/name: grafana-operator
