# Source: grafana-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-operator
  namespace: amcop-system
  labels:
    app.kubernetes.io/name: grafana-operator
    app.kubernetes.io/version: 5.0.0
automountServiceAccountToken: true
