apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vm-provisioner
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
      - namespaces
      - serviceaccounts
    verbs:
      - '*'
  - apiGroups:
      - policy.aarna.com
    resources:
      - topology5gs
    verbs:
      - '*'
  - apiGroups:
      - amcop.aarnanetworks.com
    resources:
      - installers
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - '*'
  - apiGroups:
      - k8splugin.io
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - batch
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - extensions
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - metal3.io
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: topology-cluster-role
rules:
- apiGroups:
  - config.porch.kpt.dev
  resources:
  - '*'
  verbs:
  - '*'
