apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: aai-pkg-variant
spec:
  upstream:
    repo: amcoppackages
    package: aai
    revision: v1
  downstream:
    repo: mgmt
    package: aai
  annotations:
    approval.nephio.org/policy: initial
