apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: acp-rand-pkg-variant
spec:
  upstream:
    repo: amcoppackages
    package: acp-rand
    revision: v1
  downstream:
    repo: mgmt
    package: acp-rand
  annotations:
    approval.nephio.org/policy: initial