apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: camunda-pkg-variant
spec:
  upstream:
    repo: amcoppackages
    package: camunda
    revision: v1
  downstream:
    repo: mgmt
    package: camunda
  annotations:
    approval.nephio.org/policy: initial