apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: saasdb-pkg-variant
spec:
  upstream:
    repo: amcoppackages
    package: saasdb
    revision: v1multitenant
  downstream:
    repo: mgmt
    package: saasdb
  annotations:
    approval.nephio.org/policy: initial
