apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: vm-provisioner-pkg-variant
spec:
  upstream:
    repo: amcoppackages
    package: vm-provisioner
    revision: v1
  downstream:
    repo: mgmt
    package: vm-provisioner
  annotations:
    approval.nephio.org/policy: initial