apiVersion: robinbundleoperator.example.com/v1alpha1
kind: RobinBundleOperator
metadata:
  labels:
    app.kubernetes.io/name: robinbundleoperator
    app.kubernetes.io/instance: robinbundleoperator
    app.kubernetes.io/part-of: robin-bundle-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: robin-bundle-operator
  name: robinbundleoperator
  # We can configure the verbosity level for ansible script
  # execution, this will be helpful for us to debug the ansible execution
  annotations:
    "ansible.sdk.operatorframework.io/verbosity": "2"
spec:
  meta:
    role: robinbundleoperator
    collection_size: 50G
    bundle_name: fortinet-test
    bundle_version: v2
    # Please update the correct url for fetching the robin bundle and image
    bundle_path: file:///root/robin-bundle/new_bundle/fortinet.tar.gz
    image_path: file:///root/robin-bundle/new_bundle/fortios.qcow2
    image_name: fortinet
    image_version: v1
    input_yaml_file: input-static-ip-pools.yaml
    appname: "fortinet-app"
    media: "SSD"
    # Make sure please check the robin ip pool list and availiable IPs in the robin
    # and change the value accordingly
    static_ip1: "10.2.0.52"
    static_ip2: "10.2.2.51"
    ippool1: "ovspool"
    ippool2: "sriov401"
    multinode_value: 1
    ansible_python_interpreter: /usr/bin/python3
    robin_executable_path: /root/bin/robin
    ansible_become_password: "root@2025"
    host: 10.2.0.50
    ansible_ssh_user: root
    robin_username: robin
    robin_password: Robin@108
    name_of_the_bundle: Fortinet VM
    vm_password: "robin123"
