{
 "title": "ACP Alarm Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://onedrive.live.com/embed?resid=A1A305B33D38C5E8%21253&authkey=%21AJ6_IQ3RnhjCOkI&width=1229&height=97\" width=\"1229\" height=\"97\" />"
   }
  },
  {
   "title": "Total Alarms",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(alert_severity{alarmState=\"Raised\"}) - count(alert_severity{alarmState=\"Cleared\"}) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAN Alarms - Critical",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(alert_severity{alarmState=\"Raised\", severity=\"Critical\"}) - count(alert_severity{alarmState=\"Cleared\", severity=\"Critical\"}) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAN Alarms - Major",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(alert_severity{alarmState=\"Raised\", severity=\"Major\"}) - count(alert_severity{alarmState=\"Cleared\", severity=\"Major\"}) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAN Alarms - Minor",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(alert_severity{alarmState=\"Raised\", severity=\"Minor\"}) - count(alert_severity{alarmState=\"Cleared\", severity=\"Minor\"}) OR on() vector(0)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAN Alarms - Warnings",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(alert_severity{alarmState=\"Raised\", severity=\"Info\"}) - count(alert_severity{alarmState=\"Cleared\", severity=\"Info\"}) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ACP Alarms -All-Alarms",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "targets": [
    { "expr": "alert_severity{}" }
   ]
  }
 ]
}