{
 "title": "ACP-Alarm Tables",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Active Alarms",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(alert_severity{alarmState=\"Raised\"}) - count(alert_severity{alarmState=\"Cleared\"})"
    }
   ]
  },
  {
   "title": "ACP Alarms -All-Alarms",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    { "expr": "alert_severity{}" }
   ]
  },
  {
   "title": "ACP Alarms - Critical",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "alert_severity{severity=\"Critical\"}"
    }
   ]
  },
  {
   "title": "ACP Alarms -Major-Alarms",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "alert_severity{severity=\"Major\"}"
    }
   ]
  },
  {
   "title": "ACP Alarms -Minor-Alarms",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "alert_severity{severity=\"Minor\"}"
    }
   ]
  },
  {
   "title": "ACP Alarms -Warning-Alarms",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "alert_severity{severity=\"Warning\"}"
    }
   ]
  }
 ]
}