{
 "title": "Druid-PM-Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Total throughput (UL+DL)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "targets": [
    {
     "expr": "raemis_dl_kbits_per_second_sgi_n6 + raemis_ul_kbits_per_second_sgi_n6",
     "legendFormat": "__auto"
    },
    {
     "expr": "raemis_dl_kbits_per_second_s1_n3 + raemis_ul_kbits_per_second_s1_n3",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "   UL Thpt",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "targets": [
    {
     "expr": "raemis_ul_kbits_per_second_sgi_n6",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "   DL Thpt",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "targets": [
    {
     "expr": "raemis_ul_kbits_per_second_sgi_n6",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Availability(Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "raemis_uptime_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "No of UE connected to network",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 22 },
   "targets": [
    { "expr": "raemis_attached_users", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Packet drops in network.",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 10, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "raemis_ul_dropped_packet_percentage",
     "legendFormat": "__auto"
    },
    {
     "expr": "raemis_dl_dropped_packet_percentage",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "\t UE Session stability / No of time session connected or disconnected.   ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "raemis_default_bearer_setup_success_total ",
     "legendFormat": "__auto"
    },
    {
     "expr": "raemis_default_bearer_setup_success_created",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Latency  ( Not e2e latency )",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 10, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "raemis_average_latency", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Compute resource utilization ( CPU  )",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 10, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "raemis_average_ps_cpu_usage", "legendFormat": "__auto" },
    { "expr": "raemis_max_ps_cpu_usage", "legendFormat": "__auto" }
   ]
  }
 ]
}