{
 "title": "Druid FM_Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://onedrive.live.com/embed?resid=A1A305B33D38C5E8%21253&authkey=%21AJ6_IQ3RnhjCOkI&width=1229&height=97\" width=\"1229\" height=\"97\" />"
   }
  },
  {
   "title": "Total Alarms",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(alert_Druid{EventType=\"alarm_raised\"}) OR on() vector(0)) - count(alert_Druid{EventType=\"alarm_cleared\"}) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Druid_Alarms - Critical",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(alert_Druid{EventType=\"alarm_raised\",EventInfoChar2=\"Critical\" }) OR on() vector(0)-count(alert_Druid{EventType=\"alarm_cleared\", EventInfoChar2=\"Critical\" }) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Druid_Alarms - Major",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(alert_Druid{EventType=\"alarm_raised\",EventInfoChar2=\"Major\" }) OR on() vector(0)-count(alert_Druid{EventType=\"alarm_cleared\", EventInfoChar2=\"Major\" }) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Druid_Alarms-Minor",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 9, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(alert_Druid{EventType=\"alarm_raised\",EventInfoChar2=\"Minor\" }) OR on() vector(0)-count(alert_Druid{EventType=\"alarm_cleared\", EventInfoChar2=\"Minor\" }) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Druid Alarms - Warning",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(alert_Druid{EventType=\"alarm_raised\",EventInfoChar2=\"Warning\" }) OR on() vector(0)-count(alert_Druid{EventType=\"alarm_cleared\", EventInfoChar2=\"Warning\" }) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Druid Alarms - info",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(alert_Druid {EventType=\"alarm_raised\", EventInfoChar2=\"info\"}) OR on() vector(0) )-(count(alert_Druid {EventType=\"alarm_cleared\", EventInfoChar2=\"info\"}) OR on() vector(0) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Core_All-Alarms",
   "type": "table",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 18 },
   "targets": [
    { "expr": "alert_Druid", "legendFormat": "__auto" }
   ]
  }
 ]
}