{
 "title": "Druid_FM_Table",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Active Alarms",
   "type": "stat",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(alert_Druid{alarmState=\"Raised\"}) - count(alert_Druid{alarmState=\"Cleared\"}) "
    }
   ]
  },
  {
   "title": "Core_Alarms",
   "type": "table",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 7 },
   "targets": [
    { "expr": "alert_Druid", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Core_Alarms-Critical",
   "type": "table",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "alert_Druid{EventInfoChar2=\"critical\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Core_Alarms_Major",
   "type": "table",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "alert_Druid{EventInfoChar2=\"major\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Core_Alarms_Minor",
   "type": "table",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "alert_Druid{EventInfoChar2=\"minor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Core_Alarms_warning",
   "type": "table",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "alert_Druid{EventInfoChar2=\"warning\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Core_Alarms_info",
   "type": "table",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "alert_Druid{EventInfoChar2=\"info\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}