{
 "title": "Correlation Dashboard",
 "description": "Demo dashboard for correlation details",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Fault Alarms",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "count(alert_fault{})", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Correlated Events",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(correlated_event)", "legendFormat": "__auto" }
   ]
  },
  { "title": "Correlated Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Correlated Events",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "correlated_event", "legendFormat": "__auto" }
   ]
  },
  { "title": "Fault Alarms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Fault Alarms",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "alert_fault{domain=\"fault\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}