{
 "title": "PM_Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "DRB UE Throughput Downlink (kbps)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "targets": [
    {
     "expr": "CARR_PDSCHMCSDist_1_1_0{senderName=\"DU\"} * DRB_UEVolDl / DRB_UETimeDl"
    }
   ]
  },
  {
   "title": "DRB UE Throughput Uplink (kbps)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "targets": [
    {
     "expr": "CARR_PDSCHMCSDist_1_1_0{senderName=\"DU\"} * DRB_UEVolUl / DRB_UETimeUl"
    }
   ]
  },
  {
   "title": "DRB Cell Throughput Downlink (kbps)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "targets": [
    {
     "expr": "(DRB_CellVolDl{senderName=\"DU\"} * 1000) / DRB_CellTimeDl"
    }
   ]
  },
  {
   "title": "DRB Cell Throughput Uplink (kbps)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "targets": [
    {
     "expr": "(DRB_CellVolUl{senderName=\"DU\"} * 1000) / DRB_CellTimeUl"
    }
   ]
  },
  {
   "title": "DL Total PRB Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "targets": [
    {
     "expr": "RRU_PrbTotDl{senderName=\"DU\"}"
    }
   ]
  },
  {
   "title": "UL Total PRB Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "targets": [
    {
     "expr": "RRU_PrbTotUl{senderName=\"DU\"}"
    }
   ]
  },
  {
   "title": "Cell Availability Time (Total)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(100*(1440 -(OAM_CellUnavailabilityFault + OAM_CellUnavailabilityManual)))/1440"
    }
   ]
  },
  {
   "title": "RRC Connections (Max)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "RRC_ConnMax{senderName=\"DU\"}"
    }
   ]
  },
  {
   "title": "Average IP Latency DL",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "DRB_RlcSduLatencyDl_QoSX{senderName=\"DU\"}"
    }
   ]
  }
 ]
}