{
 "title": "robin_cluster_monitor",
 "description": "Clone of https://raw.githubusercontent.com/stefanprodan/k8s-grafana/master/chart/grafana/dashboards/control-plane.json",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Cluster Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Control Plane",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 1, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"kubernetes-apiservers\"})"
    }
   ]
  },
  {
   "title": "Number of nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"kubernetes-nodes\"})"
    }
   ]
  },
  {
   "title": "Numbef of Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kubelet_running_pods", "legendFormat": "{{kubernetes_io_hostname}}" }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(cpu) (node_cpu_seconds_total{instance=\"10.2.0.50:29457\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"kubernetes-pods\"} - node_boot_time_seconds{job=~\"$job|kubernetes-pods\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 1, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)) / count(node_cpu_seconds_total{mode=\"idle\"})"
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"/dev/mapper/.*\",id=\"/\"}) / sum (container_fs_limit_bytes{device=~\"/dev/mapper/.*\",id=\"/\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes) - sum(node_memory_Buffers_bytes) - sum(node_memory_Cached_bytes)) / sum(node_memory_MemTotal_bytes)) * 100"
    }
   ]
  },
  {
   "title": "Pod Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU usage per pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory usage per pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Network receive/transmit (1m avg) per pod",
   "type": "graph",
   "description": "+ve values indicates the receive rate \n- ve value indicates the transmit rate",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Control Plane",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "API Servers UP",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(up{job=\"kubernetes-apiservers\"} == 1) / count(up{job=\"kubernetes-apiservers\"})) * 100"
    }
   ]
  },
  {
   "title": "Kube DNS UP",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(time() - container_last_seen{pod=~\"coredns.*\",container=\"coredns\"} < 30) /  2) * 100 > 30"
    }
   ]
  },
  {
   "title": "Calico Net UP",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(time() - container_last_seen{pod=~\"calico-node.*\", container=~\"calico-node\"} < 30 ) / count(up{job=\"kubernetes-nodes\"}) * 100"
    }
   ]
  },
  {
   "title": "Kubernetes nodes - up/down(1/0)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=\"kubernetes-nodes\"}",
     "legendFormat": "Node name : {{instance}}"
    }
   ]
  },
  {
   "title": "Kubernetes API Servers - Count",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(up{job=\"kubernetes-apiservers\"})"
    }
   ]
  },
  {
   "title": "Kubernetes Core-dns Count",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(time() - container_last_seen{pod=~\"coredns.*\",container=\"coredns\"} < 30)"
    }
   ]
  },
  {
   "title": "Calico  -Instance Count",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(time() - container_last_seen{pod=~\"calico-node.*\", container=~\"calico-node\"} < 30 )"
    }
   ]
  },
  {
   "title": "Kubelets UP",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(up{job=\"kubernetes-nodes\"} == 1) / count(up{job=\"kubernetes-nodes\"})) * 100"
    }
   ]
  },
  {
   "title": "APIs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Kubernetes API",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by(code) (rate(apiserver_request_total{code!=\"0\"}[5m]))",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "API Errors [1h]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{code=~\"5..\"}[1h]))"
    }
   ]
  },
  {
   "title": "Kubernetes API Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "max by (resource, verb) (rate(apiserver_request_duration_seconds_sum{verb!~\"WATCH|CONNECT\"}[5m]))  / \nmax by (resource, verb) (rate(apiserver_request_duration_seconds_count{verb!~\"WATCH|CONNECT\"}[5m]))\n",
     "legendFormat": "{{ resource }} {{ verb }}"
    }
   ]
  },
  {
   "title": "Max API Latency [1h]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max (rate(apiserver_request_duration_seconds_sum{verb!=\"WATCH\"}[1h]))  / \nmax (rate(apiserver_request_duration_seconds_count{verb!=\"WATCH\"}[1h]))"
    }
   ]
  },
  {
   "title": "POD stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Robin container CPU usage- non k8s containers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name!~\"^k8s_.*\"}[1m])) by (name,rnodetype,robinhost)",
     "legendFormat": "{{ rnodetype }} - {{ robinhost }} - {{ name }}"
    }
   ]
  },
  {
   "title": "Robin container Memory usage - non-k8s container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name!~\"^k8s_.*\"}) by (name,rnodetype,robinhost)",
     "legendFormat": "{{ rnodetype }} - {{ robinhost }} -  {{ name }}"
    }
   ]
  },
  {
   "title": "Robin container network receive/transmit  (1m avg) per pod",
   "type": "graph",
   "description": "+ve values indicates the receive rate \n- ve value indicates the transmit rate",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name!~\"^k8s_.*\"}[1m])) by (name,rnodetype,robinhost)",
     "legendFormat": "{{ rnodetype }} - {{ robinhost }} - {{ name }}"
    }
   ]
  }
 ]
}