{
 "title": "robin_cluster_alerts",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Alarms-Critical",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(alert_robin{severity=\"Critical\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alarms-Major",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(alert_robin{severity=\"Major\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alarms-Minor",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(alert_robin{severity=\"Minor\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alarms-Warning",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(alert_robin{severity=\"Warning\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Robin -All-Alarms",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "targets": [
    { "expr": "alert_robin", "legendFormat": "__auto" }
   ]
  }
 ]
}