{
 "title": "Switch_FM_Table",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Active Alarms",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(alert_csr{})" }
   ]
  },
  {
   "title": "L3 Switch-All-Alarms",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    { "expr": "alert_csr{}" }
   ]
  },
  {
   "title": "L3 Switch-Critical-Alarms",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "alert_csr{Severity=\"critical\"}"
    }
   ]
  },
  {
   "title": "L3 Switch-Major-Alarms",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "alert_csr{Severity=\"Major\"}"
    }
   ]
  },
  {
   "title": "L3 Switch-Minor-Alarms",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "alert_csr{Severity=\"Minor\"}"
    }
   ]
  },
  {
   "title": "L3 Switch-Info-Alarms",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "alert_csr{Severity=\"info\"} OR alert_csr{Severity=\"warning\"}\n"
    }
   ]
  }
 ]
}