{
 "title": "Switch_Alarm_Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://onedrive.live.com/embed?resid=A1A305B33D38C5E8%21253&authkey=%21AJ6_IQ3RnhjCOkI&width=1229&height=97\" width=\"1229\" height=\"97\" />"
   }
  },
  {
   "title": "Total Alarms",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (alert_csr) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Critical",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (alert_csr{Severity=\"critical\"}) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Major",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(alert_csr{Severity=\"major\"}) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Minor",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(alert_csr{Severity=\"major\"}) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(alert_csr{Severity=\"warning\"}) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L3 Switch-All-Alarms",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "targets": [
    { "expr": "alert_csr{}" }
   ]
  }
 ]
}