apiVersion: apps/v1
kind: Deployment
metadata:
  name: aai-grpc
  namespace: amcop-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc
  template:
    metadata:
      labels:
        app: grpc
    spec:
      containers:
      - name: envoy
        image: amcopnightly/aai-grpc:v4.0-2024-02-21
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: aai-grpc
  namespace: amcop-system
spec:
  type: NodePort
  selector:
    app: grpc
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30002