apiVersion: v1
kind: ServiceAccount
metadata:
  name: vm-provisioner
  namespace: tenant
---
# vm-provisioner-config config
apiVersion: v1
kind: ConfigMap
metadata:
  name: vm-provisioner-config
  namespace: tenant
data:
  vm-provisioner-config.json: "{    \n  \"logLevel\":       \"info\",\n  \"port\":           \"9052\",\n  \"aaiAddress\":     \"http://aai:8443/aai/v23\",\n  \"aaiUsername\":    \"AAI\",\n  \"aaiPassword\":    \"AAI\",\n  \"camundaAddress\": \"camunda:8443\",\n  \"camundaUserName\": \"souser\",\n  \"camundaPassword\": \"mypassword\",\n  \"kafkaServiceName\": \"kafka1\",\n  \"kafkaServicePort\": \"9092\"\n}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vm-provisioner
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
      - namespaces
      - serviceaccounts
    verbs:
      - '*'
  - apiGroups:
      - policy.aarna.com
    resources:
      - topology5gs
    verbs:
      - '*'
  - apiGroups:
      - amcop.aarnanetworks.com
    resources:
      - installers
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - '*'
  - apiGroups:
      - k8splugin.io
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - batch
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - extensions
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - metal3.io
    resources:
      - '*'
    verbs:
      - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vm-provisioner-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: vm-provisioner
    namespace: tenant
roleRef:
  kind: ClusterRole
  name: vm-provisioner
  apiGroup: rbac.authorization.k8s.io
---
# vm-provisioner Service
apiVersion: v1
kind: Service
metadata:
  name: vm-provisioner
  namespace: tenant
  labels:
    app: vm-provisioner
spec:
  selector:
    app: vm-provisioner
  type: ClusterIP
  ports:
    - name: vm-provisioner
      port: 9052
      targetPort: 9052
      protocol: TCP
---
# vm-provisioner Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vm-provisioner
  namespace: tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vm-provisioner
  template:
    metadata:
      labels:
        app: vm-provisioner
    spec:
      serviceAccountName: vm-provisioner
      containers:
        - name: vm-provisioner
          image: amcopnightly/vm-provisioner
          tag: v4.0-2024-02-21 "# kpt-set: ${image-tag}"
          imagePullPolicy: Always
          env: null
          ports:
            - containerPort: 9052
          volumeMounts:
            - mountPath: /opt/aes/config
              readOnly: true
              name: config
      volumes:
        - name: config
          configMap:
            name: vm-provisioner-config
